substitutions:
  server_url: !secret stillness_server_url
  api_key: !secret stillness_api_key
  ota_password: !secret stillness_ota_password
  wifi_ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password
  wifi_fallback_ssid: !secret stillness_wifi_fallback_ssid
  wifi_fallback_password: !secret stillness_wifi_fallback_password

esphome:
  name: stillness
  friendly_name: Stillness
  on_boot:
    then:
      - output.turn_on: battery_measure_en
      - delay: 200ms
      - component.update: battery_voltage
      - component.update: battery_level
      - output.turn_off: battery_measure_en
      - logger.log: "Triggering display update at boot"
      - component.update: my_online_image
  project:
    name: "oscarb.stillness"
    version: "1.0.0"

esp32:
  board: seeed_xiao_esp32s3
  framework:
    type: esp-idf 

# Enable logging
logger:

# Nake requests
http_request:
  verify_ssl: false

# Enable PSRAM support since online_image requires more than the available RAM capacity
psram:
  mode: octal
  speed: 80MHz  

# Display image
online_image:
  - url: ${server_url}
    type: BINARY
    format: png
    id: my_online_image
    update_interval: 120s
    on_download_finished:
      component.update: eink_display
    on_error:
      - logger.log: "Could not download the image"

# Enable Home Assistant API
api:
  encryption:
    key: "${api_key}"

ota:
  - platform: esphome
    password: ${ota_password}

wifi:
  ssid: "${wifi_ssid}"
  password: "${wifi_password}"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${wifi_fallback_ssid}"
    password: "${wifi_fallback_password}"

captive_portal:

# define font to display words
font:
  - file: "gfonts://Inter@700"
    id: font1
    size: 24

# define SPI interface
spi:
  clk_pin: GPIO7
  mosi_pin: GPIO9

# Battery levels
output:
  - platform: gpio
    pin: GPIO6
    id: battery_measure_en

sensor:
  - platform: adc
    pin: GPIO1
    name: "Battery voltage"
    id: battery_voltage
    update_interval: never
    unit_of_measurement: "V"
    attenuation: 12db
    filters:
      - multiply: 2.0 # The hardware uses a 1/2 voltage divider
      #- offset: 0.00  # Optional: Calibration offset if your reading is slightly off  

  - platform: template
    name: "Battery level"
    id: battery_level
    unit_of_measurement: "%"
    device_class: battery
    state_class: measurement
    lambda: 'return id(battery_voltage).state;'
    filters:
      - calibrate_linear:
          - 4.15 -> 100.0
          - 3.96 -> 90.0
          - 3.91 -> 80.0
          - 3.85 -> 70.0
          - 3.80 -> 60.0
          - 3.75 -> 50.0
          - 3.68 -> 40.0
          - 3.58 -> 30.0
          - 3.49 -> 20.0
          - 3.41 -> 10.0
          - 3.30 -> 5.0
          - 3.27 -> 0.0
      - clamp:
          min_value: 0
          max_value: 100

display:
  - platform: waveshare_epaper
    id: eink_display
    model: 7.50inv2
    cs_pin: GPIO44
    dc_pin: GPIO10
    reset_pin: GPIO38
    busy_pin: 
      number: GPIO4
      inverted: true
    update_interval: never
    lambda: |-
      it.clear();
      it.image(0, 0, id(my_online_image), COLOR_OFF, COLOR_ON); // online_image    
      //it.print(0, 0, id(font1), "Hello World!");
    